### ISSUE TITLE
Incompatibility with `@graphql-codegen/cli` version 3 and above

### ISSUE THREAD

**Issue by Brookke** [valu-digital/graphql-codegen-persisted-query-ids#10]
I recently tried updating a project that uses this plugin, however found that it did not work with the latest @graphql-codegen/cli version or anything above 3.0.0.

I get the following error:

```
✖ Invalid Codegen Configuration!
  Please make sure that your codegen config file has defined plugins list for output "dist/persisted_queri…
  It should looks like that:
  schema:
  - my-schema.graphql
  generates:
  my-file.ts:
  - plugin1
  - plugin2
  - plugin3
◼ Generate outputs
```

The config I am using is as follows

```
schema: "../../data/schema.graphql"
generates:
  gen/client.tsx:
    plugins:
      - add:
          content: "/* DO NOT EDIT! This file is auto-generated by graphql-code-generator - see `codegen.yml` */"
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"

  dist/persisted_queries/client.json:
    - graphql-codegen-persisted-query-ids:
        output: client
        algorithm: sha256
```
